/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.starter;

import lombok.extern.log4j.Log4j2;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableAuthorizationServer;

@Log4j2
@SpringBootApplication
public class App {

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
    log.info("Congrats! Your XMemeApplication server has started");
  }
}
