/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.starter;

import lombok.extern.log4j.Log4j2;
import com.crio.starter.configuration.*;

import org.springframework.context.annotation.*;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableAuthorizationServer;

@Log4j2
@SpringBootApplication
@ComponentScan(excludeFilters =
        {@ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, classes = SecurityConfiguration.class)})

public class App {

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
    log.info("Congrats! Your XMemeApplication server has started");
  }
}
